---
logging:
  level:
    ROOT: ERROR
    au.gov: DEBUG


errorRedirect: "${sourceUrl}"

jasypt:
  encryptor:
    #provider needs to be bouncycastle for this algorithm
    provider-name: "BC"
    provider-class-name: org.bouncycastle.jce.provider.BouncyCastleProvider
    algorithm: "PBEWITHSHA256AND128BITAES-CBC-BC"
    password: "testkey" #keyfilefallbackvalue
    iv-generator-classname: org.jasypt.iv.NoIvGenerator #CBC-BC does not need iv
    #TODO rotate secrets to better algorithm with iv, https://nickolasfisher.com/blog/A-Concise-Guide-to-Using-Jasypt-In-Spring-Boot-for-Configuration-Encryption
    #der style
    #privateKeyLocation: classpath:private_key.der
    #PEM style #keyfile ?
#    privateKeyFormat: PEM
#    privateKeyLocation: classpath:private_key.pem

mail:
  from: "noreply@qld.gov.au"
management:
  endpoints:
    enabled-by-default: true
    endpoint:
      health:
        enabled: true
      info:
        enabled: true
        git:
          mode: simple
    web:
      base-path: "/manage"
  server:
    add-application-context-header: false
#    servlet:
#      context-path: "/order"

noticeToPay:
  default:
    redirect: "${sourceUrl}"
  disbursementId: 999
  id:
    pattern: ".+"
  serviceWsNotify: "${serviceFullUrl}"
  serviceWsPassword: "ENC(XLW43w1vH+GlFUViiEBRCn/PvVlwlIT37w6ceV+W+rU=)"
  serviceWsUsername: "test"
  source:
    pattern: "${sourceUrl}"
notifyFormRetryCount: 3
notifyFormRetryWait: 3000
notifyFormTimeout: 3000
papiBase: "https://test.smartservice.qld.gov.au/payment"

scheduler:
  cleanup:
    deletePaidOrderDays: 60
    deleteUnpaidOrderDays: 30
    deleteUploadsDays: 60
  statusCheck:
    delay: 3600000
    maxAgeForRetry: 86400000


server:
  error:
    path: "/error"
    whitelabel:
      enabled: false
  port: 8091
  servlet:
    encoding:
      charset: "UTF-8"
      force: true
#    context-path: "/order"

serviceFranchise: "Agency franchise"
serviceFullUrl: "http://localhost:8091${web.context}"
serviceName: "Orders"
serviceWsEndpoint: "${papiBase}/service/"
serviceWsNotify: "${serviceFullUrl}/notify"
serviceWsPassword: "ENC(XLW43w1vH+GlFUViiEBRCn/PvVlwlIT37w6ceV+W+rU=)"
serviceWsUsername: "test"
sourceEncoding: "UTF-8"
sourceUrl: "http://localhost:8091/test"
#sourceUrl: "http://localhost:8091/order/test"

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testDB
    username: sa
    password:
  info:
    build:
      location: "classpath:META-INF/build-info.properties"
    git:
      location: "classpath:git.properties"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true
  mail:
    host: "localhost"
    port: 1325
  main:
    web-application-type: servlet
#  mvc:
#    servlet:
#      path: "/order"



upload:
  max: 15728640
  supported: "doc;docx;pdf;odf;jpg;jpeg;bmp;tif;tiff;png;xls;xlsx"
web:
#  context: "/order"
  context: ""

reportUri:
  reportto: "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://qldonline.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
  nel: "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}"
  csp:
    enforce: false #should be true so that it blocks inline script injection attacks etc
    upgradeInsecureRequests: ""
    default-src-data: "test.smartservice.qld.gov.au beta-static.qgov.net.au static.qgov.net.au fonts.gstatic.com www.google.com www.google.com.au stats.g.doubleclick.net www.googletagmanager.com tagmanager.google.com *.google-analytics.com https://*.gstatic.com fonts.googleapis.com ajax.googleapis.com rawgit.com code.jquery.com "
    script-src-data: "test.smartservice.qld.gov.au beta-static.qgov.net.au static.qgov.net.au  www.google.com www.googletagmanager.com tag.manager.google.com tagmanager.google.com www.google-analytics.com stats.g.doubleclick.net www.gstatic.com maps.googleapis.com fonts.googleapis.com ajax.googleapis.com code.jquery.com"
    style-src-data: "'test.smartservice.qld.gov.au beta-static.qgov.net.au static.qgov.net.au  fonts.gstatic.com www.google.com www.google.com.au stats.g.doubleclick.net www.googletagmanager.com tagmanager.google.com *.google-analytics.com https://*.gstatic.com fonts.googleapis.com ajax.googleapis.com rawgit.com code.jquery.com "
    report-url: "https://qldonline.report-uri.com/r/d/csp/reportonly"
    filter: "default-src 'self' 'unsafe-inline' data: ${reportUri.csp.default-src-data}; script-src 'nonce-[__csp_nonce]' 'strict-dynamic' 'self' 'unsafe-inline' 'unsafe-eval' data: ${reportUri.csp.script-src-data}; ${reportUri.csp.upgradeInsecureRequests} frame-ancestors 'self'; form-action 'self' www.smartservice.qld.gov.au; report-uri ${reportUri.csp.report-url};"

