name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache NVD Database
        id: cache-nvd
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            nvd-cache-${{ runner.os }}-

      - name: Get Versions
        run: |
          echo "Google chrome version"
          google-chrome --version
          echo "firefox version"
          firefox --version
          echo "temp folder: ${{ runner.temp }}"

      - name: Prep environment
        run: |
          git submodule update --init
          pushd utils/dumbster
          mvn install -Dmaven.test.skip=true -Ddependency.skip=true
          popd
          pushd utils/selenium-helper
          mvn install -Dmaven.test.skip=true -Ddependency.skip=true

      - name: Build with Maven
        run: mvn --batch-mode verify

      - run: mkdir staging && cp */target/*.war staging

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging


      - name: Cache M2 repository always
        uses: actions/cache/save@v4
        if: ${{ failure() }}
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
